apiVersion: v1
entries:
  discovery:
  - apiVersion: v2
    appVersion: 1.5.3
    created: "2024-03-27T17:49:27.089431-04:00"
    dependencies:
    - name: db
      repository: ""
      version: 1.0.0
    - name: redis
      repository: ""
      version: 1.0.0
    - name: celery-worker
      repository: ""
      version: 0.9.2
    description: The RedHat Product Discovery tool is designed to help users collect
      data about their usage of specific Red Hat software.
    digest: 2fb88cb0c5c861a0c36fa2e8978e5ca81f9c6526d50a8cd4781787784bfe3637
    icon: https://quipucords.github.io/discovery-helm-repo/charts/discovery/icon.png
    name: discovery
    type: application
    urls:
    - discovery-0.9.2.tgz
    version: 0.9.2
generated: "2024-03-27T17:49:27.088324-04:00"
