# Overlay values for Discovery

image:
  repository: "registry.redhat.io/discovery/discovery-server-rhel9"
  tag: "1.5.3"
  pullPolicy: IfNotPresent

pvc:
  db:
    requestStorage: 32Gi
  data:
    requestStorage: 8Gi
  log:
    requestStorage: 4Gi

celery-worker:
  image:
    repository: "registry.redhat.io/discovery/discovery-server-rhel9"
    tag: "1.5.3"
    pullPolicy: IfNotPresent
  autoscaling:
    minReplicas: 1

global:
  enableCeleryScanManager: "0"
