# Overlay values for Discovery

image:
  repository: "registry.redhat.io/discovery/discovery-server-rhel9"
  tag: "1.7.0"
  pullPolicy: IfNotPresent

pvc:
  db:
    requestStorage: 8Gi
  data:
    requestStorage: 8Gi
  log:
    requestStorage: 8Gi

celery-worker:
  image:
    repository: "registry.redhat.io/discovery/discovery-server-rhel9"
    tag: "1.7.0"
    pullPolicy: IfNotPresent
  autoscaling:
    minReplicas: 1
    maxReplicas: 1

global:
  enableCeleryScanManager: "0"
